### ISSUE TITLE
Signing public signed.

### ISSUE THREAD

**Issue by gh0st-1** [LeOS-GSI/R-releases#1]
i tried both your gsi out on 11/12 , they were both public signed and contained many bugs phh would keep crashing.

**Comment by LeOS-GSI** [comment]
What does 'public signed' meaning? ? And what are many bugs? ??
I think I will need details about bugs. Myself and more then 1000 other users are running LeOS on different devices as daily driver without any issue.
So, if you really know an.issue, then
-which device
- was OEM firmware installed BEFORE flashing LeOS
-  which OEM Android version was installed? A9, A10, A11 or A12? 
- which LeOS version was used
- what kind of issue? In detail with logs

Without these information I can't do anything

**Comment by LeOS-GSI** [comment]
Ok, no answer anymore. As I thought, only hot air :(

 I will close this 'fake' issue
