### ISSUE TITLE
How to get documentsui launcher back

### ISSUE THREAD

**Issue by grm34** [LeOS-GSI/R-releases#2]
Hi @LeOS-GSI 👋

I have some issues with Leos-Files on 18.1-20220721-UNOFFICIAL-treble_arm64_bvN, especially with Davx mount.

How to get documentsui launcher back in the drawer please?
I can't find any `component-override` in `/etc/sysconfig`

Thanks.

**Comment by LeOS-GSI** [comment]
It's a known issue, that the 'mounted' external storage are not persists . A workaround: you can place a short cut of the folder on desktop

If you need the DocumentsUI icon back, you must delete in /system/priv-app the DocumentsUI folder and install it manually from download folder/special_apps/apps_aosp

**Comment by grm34** [comment]
Thanks a lot. Removing `/system/priv-app/DocumentsUI/` allowed me to install it from the package manager. 🙏

**Comment by grm34** [comment]
@LeOS-GSI I was banned by mistake from the group, I sent a gif in response to the two trolls (the ones calling you gay). I'm not one of those LeOS haters, I'm using it since years now ^^
My pseudo (from matrix) @keyzer:no6tem.work

**Comment by LeOS-GSI** [comment]
I have send you an invite.

**Comment by grm34** [comment]
> I have send you an invite.

Thanks a lot 😉 I guess I'm still banned, I have an error when I try to join your invite

**Comment by LeOS-GSI** [comment]
mhm, before I have send you the invite, I have also unblocked your account. Don't know what to do more :(

**Comment by grm34** [comment]
![Screenshot_20221220-090915_Element](https://user-images.githubusercontent.com/6394023/208616166-6808b6e8-10ec-462a-849d-1d6deb61b07f.png)

**Comment by LeOS-GSI** [comment]
![photo_2022-12-20_09-45-42](https://user-images.githubusercontent.com/2726574/208623396-0193459f-c3a1-4a92-817a-2c31ba0aa68a.jpg)
![photo_2022-12-20_09-45-37](https://user-images.githubusercontent.com/2726574/208623401-1e4f0fcd-da63-49f4-a379-f7afd63a2b9c.jpg)

you are not banned anymore

**Comment by grm34** [comment]
@LeOS-GSI thanks 🙏 Can you send me another invite please, I still can see the group

**Comment by LeOS-GSI** [comment]
Ok, done.

**Comment by grm34** [comment]
Still can't see the group or any invite from matrix 😔😔😔

**Comment by grm34** [comment]
@LeOS-GSI sorry to ask again here but I still can't join the group. I think it's because I'm on matrix (I don't use TG anymore) and my homeserver still banned. No idea how bans works over bridges. Can you check for my homeserver please? `no6tem.work`

**Comment by LeOS-GSI** [comment]
I have send you once more an Invitation

**Comment by grm34** [comment]
Thank you, I received the invitation, still the same error message `CANNOT JOIN USER WHO WAS BANNED`. I investigate the problem and I tell you. According to the matrix doc if my ID is not banned anymore I should be able to join.

**Comment by LeOS-GSI** [comment]
I can't do more. Sorry
![Screenshot_20230206-195025](https://user-images.githubusercontent.com/2726574/217059772-110fb8eb-d9d5-492f-98ca-099954ce7447.png)
![Screenshot_20230206-195138](https://user-images.githubusercontent.com/2726574/217059791-5f2ec7d6-e3ea-4287-abc9-e82d8ca62e6f.png)
![Screenshot_20230206-195222](https://user-images.githubusercontent.com/2726574/217059805-40278ff5-d114-4a48-99e1-68a7a55827fc.png)


By the way. The LeOS room is closed since month, because to much Spammers are coming thru Matrix
